spring.application.name=spaceXdashboard_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/spacexdb
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.secret-key=b8f1e4a9c3d6f2e8a1b4c7d9e3f6a2b5c8d1e4f7a9b2c5d8e1f4a7b9c2e5f8a1
app.expiration-time=900000